version: '3'
volumes:
  volume-certs:
  volume-vhost:
  volume-html:

services: 
  nginx-proxy:
        #name: 'nginx-proxy'
    image: 'jwilder/nginx-proxy'
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - volume-certs:/etc/nginx/certs:ro
      - volume-vhost:/etc/nginx/vhost.d
      - volume-html:/usr/share/nginx/html
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'

  nginx-proxy-letsencrypt:
        #  name: 'nginx-proxy-letsencrypt'
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    depends_on: 
      - 'nginx-proxy'
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume-certs:/etc/nginx/certs
      - volume-vhost:/etc/nginx/vhost.d
      - volume-html:/usr/share/nginx/html

  nginx:
    image: 'nginx'        
    depends_on: 
      - 'nginx-proxy-letsencrypt'
    expose:
      - 80
    restart: always
    environment: 
      - VIRTUAL_HOST=nginx.renz.cloud
      - LETSENCRYPT_HOST=nginx.renz.cloud
      - LETSENCRYPT_EMAIL=crypto@renz.cloud
  
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    depends_on:
      - 'nginx-proxy-letsencrypt'
    hostname: 'gitlab.renz.cloud'
    environment: 
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.renz.cloud'
    environment:
      - VIRTUAL_HOST=gitlab.renz.cloud
      - LETSENCRYPT_HOST=gitlab.renz.cloud
      - LETSENCRYPT_EMAIL=crypto@renz.cloud
        #iGITLAB_OMNIBUS_CONFIG: |
  #    # Add any other gitlab.rb configuration here, each on its own lin
    expose:
      - '80'
  #  - '443'
  #  - '22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
