version: '3'
volumes:
  volume-certs:
  volume-vhost:
  volume-html:
  gitlab-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/gitlab/config'
  gitlab-logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/gitlab/logs'
  gitlab-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/gitlab/data'


services: 
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - volume-certs:/etc/nginx/certs:ro
      - volume-vhost:/etc/nginx/vhost.d
      - volume-html:/usr/share/nginx/html
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'

  nginx-proxy-letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    depends_on: 
      - 'nginx-proxy'
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume-certs:/etc/nginx/certs
      - volume-vhost:/etc/nginx/vhost.d
      - volume-html:/usr/share/nginx/html

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    depends_on:
      - 'nginx-proxy-letsencrypt'
    hostname: 'gitlab.renz.cloud'
    environment: 
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.renz.cloud'
       # Add any other gitlab.rb configuration here, each on its own line
    environment:
      - VIRTUAL_HOST=gitlab.renz.cloud
      - LETSENCRYPT_HOST=gitlab.renz.cloud
      - LETSENCRYPT_EMAIL=crypto@renz.cloud
    expose:
      - '80'
  #  - '443' # not needed, nginx-proxy talks to this container without SSL on port 80
  #  - '22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
